#include <stdio.h>

//code generated by microsoft bing & chatGPT
//just to be tested
int main()
{
    int n; //the number to be factorized
    int i = 2; //the smallest prime factor
    printf("Input a positive integer: ");
    scanf("%d", &n); //read the input from user
    printf("%d = ", n); //print the result format
    while (n > 1) //loop until n is 1
    {
        if (n % i == 0) //if i is a factor of n
        {
            printf("%d", i); //print i
            n = n / i; //divide n by i
            if (n > 1) //if n is not 1 yet
            {
                printf("x"); //print x symbol
            }
        }
        else //if i is not a factor of n
        {
            i++; //increment i by 1
        }
    }
    printf("\n"); //print a new line
    return 0;
}